[package]
name                    = "graphvizier"
version                 = "0.0.0"
edition                 = "2021"

[dependencies]
lazy_static             = "1"
regex                   = "1"
uuid                    = { version = "0.8", features = ["v4"] }
